# environment.yaml

name: base
channels:
  - defaults
  - pytorch
dependencies:
  - jupyter
  - numpy
  - pandas
  - pip
  - python=3.9
  #- tensorflow=2.6.0
  - pytorch:torchvision 
  - pytorch:torchaudio 
  - pytorch:cpuonly
  - pytorch:pytorch=1.11
  #- cudatoolkit=11.3
  #- pip:
  #  - -r file:requirements.txt
